# Generated by Django 4.2.16 on 2024-09-18 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_intake_date_intake_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, unique=True)),
                ('daily_calories', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='calorie_objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.calorieobjective'),
        ),
    ]
