# Generated by Django 4.2.16 on 2024-09-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_calorieobjective_customuser_calorie_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='personal_calorie_objective',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
